### ISSUE TITLE
rsync用法

### ISSUE THREAD

**Issue by hujianli94** [lework/reference#4]
#### 提供参考资料地址

提供更多参考资料有助于我们整理成速查表(备忘单)

- 提供参考地址 
https://wiki.archlinuxcn.org/wiki/Rsync
https://rsync.samba.org/examples.html
https://www.ruanyifeng.com/blog/2020/08/rsync.html

- 提供官网地址 
https://rsync.samba.org/

**Comment by lework** [comment]
https://quickref.leops.cn/rsync.html
