### ISSUE TITLE
请求nginx速查表添加内容: 编译参数 第三方模块链接

### ISSUE THREAD

**Issue by wolf-li** [lework/reference#8]
#### 提供参考资料地址

提供更多参考资料有助于我们整理成速查表(备忘单)

- 提供参考地址 https://blog.horus-k.com/2020/07/24/Nginx/nginx%E8%AF%A6%E7%BB%86%E7%BC%96%E8%AF%91%E5%8F%82%E6%95%B0/
- 第三方模块官网地址 https://www.nginx.com/resources/wiki/modules/

**Comment by lework** [comment]
加上了。
